[package]
name = "projekt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn_partial_eq = "0.1.2"
egui-tetra = "0.3.0"
tetra = "0.6.7"
petgraph = "0.6.0"
rand = "0.8.5"
